# Generated by Django 4.2.6 on 2024-01-05 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nguoidung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='chucvu',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='nguoidung.chucvu'),
        ),
    ]
