# Generated by Django 4.2.6 on 2024-01-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nguoidung', '0002_nguoidung_chucvu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguoidung',
            name='chucvu',
        ),
    ]
