# Generated by Django 4.2.6 on 2024-01-09 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nguoidung', '0003_remove_nguoidung_chucvu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChucVu',
        ),
    ]
