# Generated by Django 4.2.6 on 2024-01-23 10:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0002_khoaluan_hoidongbaove_diemkhoaluan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='diemkhoaluan',
            name='nhanxet',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
