# Generated by Django 4.2.6 on 2024-01-24 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khoaluan',
            name='giangvienhuongdan',
        ),
        migrations.RemoveField(
            model_name='khoaluan',
            name='sinhvienthuchien',
        ),
        migrations.CreateModel(
            name='SinhVienThucHien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('khoaluan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='thesis.khoaluan')),
                ('sinhvien', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sinhvien', 'khoaluan')},
            },
        ),
        migrations.CreateModel(
            name='GiangVienHuongDan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('giangvien', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('khoaluan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='thesis.khoaluan')),
            ],
            options={
                'unique_together': {('giangvien', 'khoaluan')},
            },
        ),
        migrations.AddField(
            model_name='khoaluan',
            name='giangvien',
            field=models.ManyToManyField(related_name='khoaluan_gv', through='thesis.GiangVienHuongDan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='khoaluan',
            name='sinhvien',
            field=models.ManyToManyField(related_name='khoaluan_sv', through='thesis.SinhVienThucHien', to=settings.AUTH_USER_MODEL),
        ),
    ]
