# Generated by Django 4.2.6 on 2024-01-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0005_remove_khoaluan_giangvienhuongdan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoidongbaove',
            name='tenhoidong',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
