# Generated by Django 4.2.6 on 2024-01-28 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0007_khoaluan_baikhoaluan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TieuChiChamDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('hinhthuc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('noidung', models.DecimalField(decimal_places=2, max_digits=5)),
                ('baove', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diemchinhthuc', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='diemkhoaluan',
            name='diem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diemkhoaluan', to='thesis.tieuchichamdiem'),
        ),
    ]
