# Generated by Django 4.2.6 on 2024-01-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0008_tieuchichamdiem_alter_diemkhoaluan_diem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tieuchichamdiem',
            old_name='baove',
            new_name='tieuchi1',
        ),
        migrations.RenameField(
            model_name='tieuchichamdiem',
            old_name='hinhthuc',
            new_name='tieuchi2',
        ),
        migrations.RenameField(
            model_name='tieuchichamdiem',
            old_name='noidung',
            new_name='tieuchi3',
        ),
        migrations.AlterField(
            model_name='diemkhoaluan',
            name='diem',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
