# Generated by Django 4.2.6 on 2024-01-09 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhoaLuan',
            fields=[
                ('idkhoaluan', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('tenkhoaluan', models.CharField(max_length=255)),
                ('ngaybaove', models.DateField()),
                ('dabaove', models.BooleanField(default=False)),
                ('giangvienhuongdan', models.ManyToManyField(related_name='giangvienhuongdan', to=settings.AUTH_USER_MODEL)),
                ('sinhvien', models.ManyToManyField(related_name='sinhvienkhoaluan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
